Backwards compatibility for ST3
ST3 throws the following error because f-strings require Python 3.6+
```
reloading plugin Sass.sass_completions
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 125, in reload_plugin
    m = importlib.import_module(modulename)
  File "./python3.3/importlib/__init__.py", line 90, in import_module
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 1199, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "/Users/roblav96/Library/Application Support/Sublime Text 3/Installed Packages/Sass.sublime-package/sass_completions.py", line 688
    details = f"<code>{prop}</code> property-value"
                                                  ^
SyntaxError: invalid syntax
```